// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tunarrly.Infrastructure.Data;

#nullable disable

namespace Tunarrly.Infrastructure.Data.Migrations
{
    [DbContext(typeof(TunarrlyDbContext))]
    partial class TunarrlyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Tunarrly.Infrastructure.Data.AiRecommendationRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputSummaryJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderBaseUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AiRecommendationRuns");
                });

            modelBuilder.Entity("Tunarrly.Infrastructure.Data.AppSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("Tunarrly.Infrastructure.Data.ArtistRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RelationType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceArtistName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceNormalizedName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetArtistName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetNormalizedName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SourceNormalizedName", "TargetNormalizedName", "RelationType");

                    b.ToTable("ArtistRelations");
                });

            modelBuilder.Entity("Tunarrly.Infrastructure.Data.LibraryAlbum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArtistId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId", "NormalizedTitle");

                    b.ToTable("LibraryAlbums");
                });

            modelBuilder.Entity("Tunarrly.Infrastructure.Data.LibraryArtist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MusicBrainzId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("LibraryArtists");
                });

            modelBuilder.Entity("Tunarrly.Infrastructure.Data.LibraryTrack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AlbumId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("FileHash")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FileModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genre")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MainArtistId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("MainArtistId");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("LibraryTracks");
                });

            modelBuilder.Entity("Tunarrly.Infrastructure.Data.LidarrArtist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ForeignArtistId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("LidarrId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MetadataProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Monitored")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MusicBrainzId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.Property<int?>("QualityProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LidarrId")
                        .IsUnique();

                    b.HasIndex("NormalizedName");

                    b.ToTable("LidarrArtists");
                });

            modelBuilder.Entity("Tunarrly.Infrastructure.Data.Recommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArtistName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Confidence")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GenresJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastCalculatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedArtistName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasonJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RelatedArtistsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedArtistName")
                        .IsUnique();

                    b.ToTable("Recommendations");
                });

            modelBuilder.Entity("Tunarrly.Infrastructure.Data.ScanJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrentFile")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureSummaryJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FilesDiscovered")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FilesFailed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FilesScanned")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FilesSkipped")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LibraryPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ScanJobs");
                });

            modelBuilder.Entity("Tunarrly.Infrastructure.Data.TrackArtistCredit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArtistName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreditType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedArtistName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TrackId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedArtistName");

                    b.HasIndex("TrackId");

                    b.ToTable("TrackArtistCredits");
                });

            modelBuilder.Entity("Tunarrly.Infrastructure.Data.LibraryAlbum", b =>
                {
                    b.HasOne("Tunarrly.Infrastructure.Data.LibraryArtist", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("Tunarrly.Infrastructure.Data.LibraryTrack", b =>
                {
                    b.HasOne("Tunarrly.Infrastructure.Data.LibraryAlbum", "Album")
                        .WithMany()
                        .HasForeignKey("AlbumId");

                    b.HasOne("Tunarrly.Infrastructure.Data.LibraryArtist", "MainArtist")
                        .WithMany()
                        .HasForeignKey("MainArtistId");

                    b.Navigation("Album");

                    b.Navigation("MainArtist");
                });

            modelBuilder.Entity("Tunarrly.Infrastructure.Data.TrackArtistCredit", b =>
                {
                    b.HasOne("Tunarrly.Infrastructure.Data.LibraryTrack", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");
                });
#pragma warning restore 612, 618
        }
    }
}
